spring:
  application:
    name: homo-sapiens
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${HS_DB_STRING_CONEXAO:jdbc:postgresql://localhost:5432/postgres?currentSchema=public}
    username: ${HS_DB_USERNAME:postgres}
    password: ${HS_DB_PASSWORD:restinga@2025}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect