spring:
  application:
    name: homo-sapiens
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${HS_DB_STRING_CONEXAO:jdbc:postgresql://localhost:5432/postgres?currentSchema=public}
    username: ${HS_DB_USERNAME:postgres}
    password: ${HS_DB_PASSWORD:restinga@2025}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      #uri: mongodb://<username>:<password>@<host>:<port>/<database>
      database: javaluan
      host: localhost
      port: 27017
      username: javaluan
      password: '123123'
      authentication-database: javaluan
amqp:
    neandertal:
      listener-queue: fila-novo-neandertal
      producer-queue: fila-retorno-neandertal